version: '3'

services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: stockplatform
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_NAME=stockplatform
      - DATABASE_ROOT_PASSWORD=mysql
      - MYSQL_PORT=3306
      - RUN_ENVIRONMENT=DOCKER
    volumes:
      - ./backend:/root/backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    environment:
      - VUE_APP_API_URL=http://backend:8000
    ports:
      - "8080:8080"
    volumes:
      - ./front:/root/frontend
      - /root/frontend/node_modules

volumes:
  mysql_data: