version: '3'

services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      - RUN_ENVIRONMENT=DOCKER
    volumes:
      - ./backend:/root/backend
    ports:
      - "${BACKEND_PORT}:8000"

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:8080"
    volumes:
      - ./front:/root/frontend
      - /root/frontend/node_modules

volumes:
  mysql_data: