# Generated by Django 5.1.4 on 2025-01-15 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="manage",
            fields=[
                ("manage_id", models.AutoField(primary_key=True, serialize=False)),
                ("manage_name", models.CharField(max_length=20, unique=True)),
                ("manage_password", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "manage",
                "db_table": "manage",
            },
        ),
        migrations.CreateModel(
            name="stock_basic",
            fields=[
                (
                    "stock_code",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("stock_name", models.CharField(max_length=20)),
                ("industry", models.CharField(max_length=20, null=True)),
                ("area", models.CharField(max_length=20, null=True)),
                ("list_date", models.CharField(max_length=8)),
                ("update_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "stock basic",
                "db_table": "stock_basic",
            },
        ),
        migrations.CreateModel(
            name="user_accounts",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_email", models.EmailField(max_length=254, unique=True)),
                ("user_name", models.CharField(max_length=40)),
                ("user_password", models.CharField(max_length=128)),
                ("user_balance", models.FloatField(default=200000.0)),
                ("user_age", models.IntegerField(null=True)),
                (
                    "user_sex",
                    models.IntegerField(choices=[(0, "男"), (1, "女")], null=True),
                ),
                ("phone_number", models.CharField(max_length=15, null=True)),
                ("address", models.CharField(max_length=100, null=True)),
                ("remark", models.TextField(max_length=500, null=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "user accounts",
                "db_table": "user_accounts",
            },
        ),
        migrations.CreateModel(
            name="stock_market",
            fields=[
                ("market_id", models.AutoField(primary_key=True, serialize=False)),
                ("stock_code", models.CharField(max_length=9)),
                ("trade_date", models.CharField(max_length=8)),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("pct_chg", models.FloatField()),
                ("vol", models.IntegerField()),
                ("amount", models.FloatField()),
            ],
            options={
                "verbose_name": "stock market",
                "db_table": "stock_market",
                "indexes": [
                    models.Index(
                        fields=["stock_code", "trade_date"],
                        name="stock_marke_stock_c_446ffc_idx",
                    )
                ],
                "unique_together": {("stock_code", "trade_date")},
            },
        ),
        migrations.CreateModel(
            name="stock_transactions",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "transaction_type",
                    models.IntegerField(choices=[(0, "买入"), (1, "卖出")]),
                ),
                ("stock_code", models.CharField(max_length=9)),
                ("stock_name", models.CharField(max_length=20)),
                ("transaction_number", models.IntegerField()),
                ("per_price", models.FloatField()),
                ("gains", models.FloatField(default=0)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="platform_functions.user_accounts",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock transactions",
                "db_table": "stock_transactions",
            },
        ),
        migrations.CreateModel(
            name="stock_ownership",
            fields=[
                ("ownership_id", models.AutoField(primary_key=True, serialize=False)),
                ("stock_code", models.CharField(max_length=9)),
                ("stock_name", models.CharField(max_length=20)),
                ("hold_number", models.IntegerField()),
                ("purchase_per_price", models.FloatField()),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="platform_functions.user_accounts",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock ownership",
                "db_table": "stock_ownership",
            },
        ),
    ]
