# Generated by Django 5.1.4 on 2025-02-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("platform_functions", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="manage",
            new_name="manager",
        ),
        migrations.AlterModelOptions(
            name="manager",
            options={"verbose_name": "manager"},
        ),
        migrations.RenameField(
            model_name="manager",
            old_name="manage_id",
            new_name="manager_id",
        ),
        migrations.RenameField(
            model_name="manager",
            old_name="manage_name",
            new_name="manager_name",
        ),
        migrations.RenameField(
            model_name="manager",
            old_name="manage_password",
            new_name="manager_password",
        ),
        migrations.AlterModelTable(
            name="manager",
            table="manager",
        ),
    ]
