# Generated by Django 5.1.4 on 2025-04-14 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_functions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_favorite_stocks",
            fields=[
                (
                    "favorite_stock_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("stock_code", models.CharField(max_length=9)),
                ("add_time", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_stocks",
                        to="platform_functions.user_accounts",
                    ),
                ),
            ],
            options={
                "verbose_name": "user favorite stocks",
                "db_table": "user_favorite_stocks",
            },
        ),
    ]
